#pragma once

#define DO_STR(x) #x
#define STR(x) DO_STR(x)

#define JULIANANFC_VERSION_MAJOR	2
#define JULIANANFC_VERSION_MINOR	1
#define JULIANANFC_VERSION_PATCH	0

#define JULIANANFC_VERSION_NUM		JULIANANFC_VERSION_MAJOR,JULIANANFC_VERSION_MINOR,JULIANANFC_VERSION_PATCH,0
#define JULIANANFC_VERSION_STR		STR(JULIANANFC_VERSION_MAJOR) L"." \
									STR(JULIANANFC_VERSION_MINOR) L"." \
									STR(JULIANANFC_VERSION_PATCH)
#define JULIANANFC_VERSION_STR_FULL	JULIANANFC_VERSION_STR
